### ISSUE TITLE
PWA issue

### ISSUE THREAD

**Issue by vahidtakro** [ThangHuuVu/thvu-blog#23]
Thanks for providing nice features on this template! I am also using same template as you. and I used to setup PWA same as you did.
my problem is that PWA wants to load everything and download all 230 MB (in my case), before showing the download to desktop icon, I don't know how to disable cache, and let PWA works before downloading everything.

[My blog](https://testingvahid.vercel.app/)

![Cajhpture](https://user-images.githubusercontent.com/40500566/133689486-44bb96e0-890a-40de-be97-91f809bd9abf.PNG)

**Comment by ThangHuuVu** [comment]
Hi, I'm not sure if this is the right place to ask. If I get it right, your issue is big cache storage. You can prevent `next-pwa` from creating precache the big resources by setting `publicExcludes` option:
> publicExcludes - an array of glob pattern strings to exclude files in the public folder from being preached. default: ['!noprecache/**/*'] - this means that the default behavior will precache all the files inside your public folder but files inside /public/noprecache folder. You can simply put files inside that folder to not precache them without config this.
    example: ['!img/super-large-image.jpg', '!fonts/not-used-fonts.otf']

Learn more at: https://github.com/shadowwalker/next-pwa#available-options
About A2HS button showing up after cache is downloaded, I could not find any related resources about this information. You'll have to dig deeper here; although I think it's kinda weird behavior, since A2HS purpose is to make the app more accessible, not working offline or cache-related.
I'm going to close the issue. Good luck with your solution!
